### YamlMime:ManagedReference

# references to external resources
resources:
  repositories:
    - repository: templates
      type: git
      name: fasttrack-docs/fasttrack-docs
      ref: refs/heads/master

# trigger on merges into these branches
trigger:
- master
- staging

jobs:

# we need to build staging content changes with master app branch for internal
# audience: content contributors
# https://ftdocs-internal-staging.azurewebsites.net
- job: Build_Staging_Changes_Internal
  condition: eq(variables['build.sourceBranch'], 'refs/heads/staging')
  pool: Hosted VS2017
  steps:
  - template: ci-pipeline-template.yml@templates
    parameters:
      audience: 'internal'
      app_branch: 'master'
      content_branch: 'staging'
      deploy_azure_connection: 'fasttrack-cms-prod'
      deploy_azure_app: 'ftdocs-internal-staging'
      deploy_azure_group: 'ftdocs-wus'
      header_id: 'FastTrackCustomHeader-internal'
      insights_key: '00000000-0000-0000-0000-000000000000'  # Internal Staging Insights Key
      storage_key_name: 'AzureStorageKey'
      storage_account: 'ftdocsblob'
      copy_search_content: 'false'
      search_api_key_name: 'SiteSearchQueryKey'
      search_server_name: 'ftdocs-search'

# we need to build staging content changes with master app branch for partner
# audience: content contributors
# https://ftdocs-partner-staging.azurewebsites.net
- job: Build_Staging_Changes_Partner
  condition: eq(variables['build.sourceBranch'], 'refs/heads/staging')
  pool: Hosted VS2017
  steps:
  - template: ci-pipeline-template.yml@templates
    parameters:
      audience: 'partner'
      app_branch: 'master'
      content_branch: 'staging'
      deploy_azure_connection: 'fasttrack-cms-prod'
      deploy_azure_app: 'ftdocs-partner-staging'
      deploy_azure_group: 'ftdocs-wus'
      header_id: 'FastTrackCustomHeader-partner'
      insights_key: '00000000-0000-0000-0000-000000000000'  # Partner Staging Insights Key
      storage_key_name: 'AzureStorageKey'
      storage_account: 'ftdocsblob'
      copy_search_content: 'false'
      search_api_key_name: 'SiteSearchQueryKey'
      search_server_name: 'ftdocs-search'

# we need to build master content changes with dev app branch for internal
# audience: cms development team
# https://internal-dev-wus.azurewebsites.net
- job: Build_Master_Changes_Internal
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  pool: Hosted VS2017
  steps:
  - template: ci-pipeline-template.yml@templates
    parameters:
      audience: 'internal'
      app_branch: 'dev'
      content_branch: 'master'
      deploy_azure_connection: 'fasttrack-cms-dev'
      deploy_azure_app: 'internal-dev-wus'
      deploy_azure_group: 'ftdocs-dev-wus'
      header_id: 'FastTrackCustomHeader-internal-dev'
      insights_key: '2996a476-14e5-49a7-9932-b3fbbe65683e'  # Internal Dev Insights Key
      template_branch: 'dev'
      storage_key_name: 'AzureStorageKey-Dev'
      storage_account: 'ftdocsdev'
      copy_search_content: 'true'
      search_api_key_name: 'SiteSearchQueryKey-Dev'
      search_server_name: 'ftdocs-search-dev'

# we need to build master content changes with dev app branch for partner
# audience: cms development team
# https://partner-dev-wus.azurewebsites.net
- job: Build_Master_Changes_Partner
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  pool: Hosted VS2017
  steps:
  - template: ci-pipeline-template.yml@templates
    parameters:
      audience: 'partner'
      app_branch: 'dev'
      content_branch: 'master'
      deploy_azure_connection: 'fasttrack-cms-dev'
      deploy_azure_app: 'partner-dev-wus'
      deploy_azure_group: 'ftdocs-dev-wus'
      header_id: 'FastTrackCustomHeader-partner-dev'
      insights_key: '550322a3-30a5-409d-a511-07913be52fc9'  # Partner Dev Insights Key
      storage_key_name: 'AzureStorageKey-Dev'
      storage_account: 'ftdocsdev'
      copy_search_content: 'true'
      search_api_key_name: 'SiteSearchQueryKey-Dev'
      search_server_name: 'ftdocs-search-dev'
