name: Pull Request Validation
# This workflow is triggered on pull requests to the repository.
on: 
  pull_request:
    branches:
      - staging

jobs:
  build:
    # Job name is "Validate Markdown"
    name: Validate Markdown
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: ./
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1  
        with:
          files: .
          config_file: "workflows/md-lint/config-relaxed.json"
          ignore_files: "examples/ignore/*"
          rules: "workflows/md-lint/rules.js"
        id: markdown
      # This step prints an output (time) from the previous step's action.
      - name: Echo the markdown validation time
        run: echo 'The time was ${{ steps.markdown.outputs.time }}.'
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Hello world action step
      id: hello
      uses: willknoll/fantastic-umbrella@master
      with:
        who-to-greet: 'Bubba'
        token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `hello` step 
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"