name: Pull Request Validation
# This workflow is triggered on pull requests to the repository.
on: 
  pull_request:
    branches:
      - staging

jobs:
  markdown_validation:
    # Job name is "Validate Markdown"
    name: Validate Markdown
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: ./
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: "workflows/md-lint/config-relaxed.json"
          ignore_files: "contribute/*"
          rules: "workflows/md-lint/rules.js"
        id: markdown
      # This step prints an output (time) from the previous step's action.
      - name: Echo the markdown validation time
        run: echo 'The time was ${{ steps.markdown.outputs.time }}.'
  run_filechecks:
    runs-on: ubuntu-latest
    name: Validate Files
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Check file names and types
      id: filevalidate
      uses: willknoll/fantastic-umbrella@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        file-size-limit: "1048576" # 1MB
        configuration-path: "some/path"
  dump_info:
    runs-on: ubuntu-latest
    name: Dump workflow info
    steps:
      - name: List files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files?per_page=3000"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"